### ISSUE TITLE
Auth Provider

### ISSUE THREAD

**Issue by TranNhatQuang2405** [TranNhatQuang2405/job_here_web#15]
- [x] Tạo authprovider
- [x] Gắn các Api xác thực người dùng

**Comment by quangphatt** [comment]
AuthProvider https://github.com/TranNhatQuang2405/job_here_web/commit/72ecaeff8a4dbefcd2b6bd73e536ce541a9196a7

**Comment by quangphatt** [comment]
Add API SignIn https://github.com/TranNhatQuang2405/job_here_web/commit/0b1ec6c5655836819d8eed86c4c37d40956618ba
