### ISSUE TITLE
Create common layout

### ISSUE THREAD

**Issue by TranNhatQuang2405** [TranNhatQuang2405/job_here_web#2]
- [x] Header
- [x] Footer
- [x] Right Menu

**Comment by quangphatt** [comment]
Header + Right Menu
https://github.com/TranNhatQuang2405/job_here_web/commit/6fea96d6f0bbdab527a3cd655d3c34b549c0553c

**Comment by quangphatt** [comment]
Footer, edit Header
https://github.com/TranNhatQuang2405/job_here_web/commit/fc1948c00805383674fc0ec20fcbf13e3d0ec650
