### ISSUE TITLE
Auth Component

### ISSUE THREAD

**Issue by TranNhatQuang2405** [TranNhatQuang2405/job_here_web#3]
- [x] Sign In Page
- [x] Sign Up Page
- [x] Reset Password Page
- [x] Authtication Code Page

**Comment by quangphatt** [comment]
SignInPage, SignUpPage https://github.com/TranNhatQuang2405/job_here_web/commit/262ecbf557f595d8366ef34f25fbfdc406da4b51

**Comment by quangphatt** [comment]
ResetPasswordPage https://github.com/TranNhatQuang2405/job_here_web/commit/e4308a8d56db4eeff45e88009168e833040d157e
