### ISSUE TITLE
Job Component

### ISSUE THREAD

**Issue by TranNhatQuang2405** [TranNhatQuang2405/job_here_web#4]
- [x] Show list job
- [x] job component

**Comment by quangphatt** [comment]
JobItem https://github.com/TranNhatQuang2405/job_here_web/commit/5e06cf44f789901645f8cdeb609df29f5e4560a6

**Comment by quangphatt** [comment]
JobList https://github.com/TranNhatQuang2405/job_here_web/commit/5f784a826a8b6b6a0913f7a61c74e12f404d838f
